In [1]:
import numpy as np

In [2]:
np.random.seed(0)

In [3]:
x = np.random.randint(5, size=(4,4))
x

array([[4, 0, 3, 3],
       [3, 1, 3, 2],
       [4, 0, 0, 4],
       [2, 1, 0, 1]])

In [6]:
x[2,1] = 7
x

array([[4, 0, 3, 3],
       [3, 1, 3, 2],
       [4, 7, 0, 4],
       [2, 1, 7, 1]])

In [7]:
x[1,3] = 5
x

array([[4, 0, 3, 3],
       [3, 1, 3, 5],
       [4, 7, 0, 4],
       [2, 1, 7, 1]])

In [10]:
x_copy = np.copy(x[2,:])
x_copy

array([4, 7, 0, 4])

In [13]:
x_reshap = x.reshape(2,8)
x = x_reshap
x

array([[4, 0, 3, 3, 3, 1, 3, 5],
       [4, 7, 0, 4, 2, 1, 7, 1]])