In [1]:
import numpy as np

In [2]:
list1 = [2, 8, 7, 11]
Q1 = np.array(list1)
Q1

array([ 2,  8,  7, 11])

In [3]:
Q2 = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]], dtype=int)
Q2

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [4]:
Q3 = np.array([Q2[:,1]])
Q3 = Q3.reshape((3,1))
Q3

array([[2],
       [5],
       [8]])

In [31]:
np.random.seed(6)
Q4 = np.random.randint(10, size = (5,6))
Q4

array([[9, 3, 4, 0, 9, 1],
       [9, 1, 4, 1, 8, 2],
       [4, 2, 5, 9, 6, 2],
       [5, 5, 1, 4, 5, 0],
       [2, 2, 3, 5, 9, 5]])

In [39]:
Q5 = np.array(Q4[0:3,1:3])
Q5

array([[3, 4],
       [1, 4],
       [2, 5]])

In [41]:
Q6 = np.array(Q4[3:,2:5])
Q6

array([[1, 4, 5],
       [3, 5, 9]])

In [40]:
Q7 = np.array(Q4[2:4,1:3])
Q7

array([[2, 5],
       [5, 1]])

In [37]:
Q8 = np.array(Q4[:,2:4])
Q8

array([[[4, 0],
        [4, 1],
        [5, 9],
        [1, 4],
        [3, 5]]])

In [38]:
Q9 = np.array(Q4[3:,:])
Q9

array([[[5, 5, 1, 4, 5, 0],
        [2, 2, 3, 5, 9, 5]]])