In [1]:
import numpy as np

In [2]:
# Create an array of even integers two through sixteen called q1.
# Index that array to obtain the following [14,6,12]

q1 = np.arange(2,17,2)
Q1 = [q1[6],q1[2],q1[5]]

In [3]:
# Create the following array called q2
# Then index q1 with q2.  Assign it to Q2.

q2 = np.array([[1,3,2],[0,7,4]])
Q2 = q1[q2]

In [4]:
# Reshape q1 into a four by two array.  Assign it to Q3.

Q3 = np.reshape(q1,(4,2))

In [5]:
# Index Q3 to obtain the following array: [4,2]

Q4 = np.array([Q3[0,1],Q3[0,0]])

In [6]:
# Index Q3 to obtaining the following array:

Q5 = np.array([[Q3[0,0]],[Q3[1,0]]])

In [7]:
#Set a random seed of 6.  
#Create an array of ten random integers 0 through 9. Then sort the array so the values are in numerical order. Assign it to Q6.
#Create a four by five array of random integers 0 through 9 and call it q7. 
#Then sort the array by columns.  Assign it to Q7.
#Now sort the q7 array by rows.  Assign it to Q8.

np.random.seed(6)
q6 = np.random.randint(10, size=10)
Q6 = np.sort(q6,axis=None)

array([0, 1, 1, 1, 3, 4, 4, 9, 9, 9])

In [8]:
q7 = np.random.randint(10,size=(4,5))
Q7 = np.sort(q7,axis=0)

array([[2, 2, 4, 5, 8],
       [2, 5, 5, 6, 9],
       [0, 1, 2, 4, 5],
       [2, 3, 5, 5, 9]])

In [9]:
Q8 = np.sort(q7,axis=1)

array([[1, 2, 2, 0, 2],
       [2, 3, 4, 2, 5],
       [8, 4, 5, 5, 5],
       [9, 6, 5, 9, 5]])

In [10]:
q9 = np.array([('Grape','Purple',3), ('Apple','Red',2), ('Banana','Yellow',1)], dtype=[('Fruit', 'U20'), ('Color', 'U20'), ('Ranking', 'int16')])

array([('Grape', 'Purple', 3), ('Apple', 'Red', 2),
       ('Banana', 'Yellow', 1)],
      dtype=[('Fruit', '<U20'), ('Color', '<U20'), ('Ranking', '<i2')])

In [12]:
Q9 = q9['Color']

array(['Purple', 'Red', 'Yellow'], dtype='<U20')

In [13]:
Q10 = q9[2]

('Banana', 'Yellow', 1)

In [18]:
# Index q9 by all Ranking’s less than 3.  Assign it to Q11.

Q11 = q9[q9['Ranking'] < 3]

array([('Apple', 'Red', 2), ('Banana', 'Yellow', 1)],
      dtype=[('Fruit', '<U20'), ('Color', '<U20'), ('Ranking', '<i2')])