In [1]:
import numpy as np

In [2]:
np.random.seed(77)

In [3]:
Q1 = np.random.randint(51, size=(8,6))

array([[23, 31, 20, 20, 43, 37],
       [24, 31, 32, 39, 44, 19],
       [32, 36, 36, 47, 14, 15],
       [10,  7, 35,  1, 11, 17],
       [ 6, 20, 37, 33, 40,  1],
       [42,  4, 29, 41, 28,  0],
       [28, 40, 25, 37, 11,  3],
       [18, 36, 21, 22, 45, 14]])

In [4]:
Q2 = np.array(Q1[2:7,4:])

array([[14, 15],
       [11, 17],
       [40,  1],
       [28,  0],
       [11,  3]])

In [5]:
Q3 = np.array(Q1[2:,3:5])

array([[47, 14],
       [ 1, 11],
       [33, 40],
       [41, 28],
       [37, 11],
       [22, 45]])

In [6]:
Q4 = Q3.reshape(2,6)

array([[47, 14,  1, 11, 33, 40],
       [41, 28, 37, 11, 22, 45]])

In [7]:
Q5 = Q4.reshape(3,4)

array([[47, 14,  1, 11],
       [33, 40, 41, 28],
       [37, 11, 22, 45]])

In [10]:
Q6 = np.array([('Janetta','Lydia',58,58), ('Deb','Albin',68,50), ('Minato','Vanja',78,38), ('Maurine','Peter',77,57), ('Niketas','Justine',70,60)], dtype=[('Name', 'U20'), ('Last', 'U20'), ('Height', 'int16'), ('Age', 'int16')])

array([('Janetta', 'Lydia', 58, 58), ('Deb', 'Albin', 68, 50),
       ('Minato', 'Vanja', 78, 38), ('Maurine', 'Peter', 77, 57),
       ('Niketas', 'Justine', 70, 60)],
      dtype=[('Name', '<U20'), ('Last', '<U20'), ('Height', '<i2'), ('Age', '<i2')])